export const PRODCUT_LIST_REQUEST = "PRODCUT_LIST_REQUEST";
export const PRODCUT_LIST_SUCCESS = "PRODCUT_LIST_SUCCESS";
export const PRODCUT_LIST_FAIL = "PRODCUT_LIST_FAIL";

export const PRODCUT_DETAIL_REQUEST = "PRODCUT_DETAIL_REQUEST";
export const PRODCUT_DETAIL_SUCCESS = "PRODCUT_DETAIL_SUCCESS";
export const PRODCUT_DETAIL_FAIL = "PRODCUT_DETAIL_FAIL";
